apiVersion: batch/v1
kind: Job
metadata:
  name: hot-mobile-e2e-tests
  namespace: hot-e2e-tests
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
  labels:
    app: playwright-tests
spec:
  template:
    spec:
      containers:
      - name: playwright-tests
        image: hot-mobile-tests:v6
        imagePullPolicy: IfNotPresent # Use cached only if exact tag matches
        env:
        - name: LANG
          value: "he_IL.UTF-8"
        - name: LC_ALL
          value: "he_IL.UTF-8"
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
        # Override the CMD in Dockerfile
        command: ["/bin/bash", "-c"]
        args:
          - "python -m pytest e2e/mobile/login/login_invalid_otp.py -v --capture=no --html=/test-results/report.html"
        volumeMounts:
        - name: test-results
          mountPath: /test-results
      volumes:
      - name: test-results
        persistentVolumeClaim:
          claimName: hot-e2e-test-results
      restartPolicy: Never
  backoffLimit: 1
